### ISSUE TITLE
Vocalink version number

### ISSUE THREAD

**Issue by regisbsb** [pauldambra/ModulusChecker#1]
Hi @pauldambra,

May I ask you to reference the version of the vocalink in your read me from http://www.vocalink.com/media/713666/vocalink_-_validating_account_numbers_v3.30.pdf that you have used please? 
Is it 3.20? It looks like it is from the fork.

**Comment by pauldambra** [comment]
It really should be in the README! That was an oversight. And it's quite a while since I last synchronised with vocalink so I don't remember which version. Probably easiest to update to 3.3 data and ensure test cases are still covered.

I definitely don't have time to update to 3.3 this weekend but it is needed. Pull requests are awesome if you have time!

P

**Comment by pauldambra** [comment]
I've just published v1.1 of the package that updates to v3.3
