### ISSUE TITLE
Sort code 232323

### ISSUE THREAD

**Issue by chinthaka** [pauldambra/ModulusChecker#13]
Why the modulus checker let pass for sort code 232323 with any account number?
Thanks

**Comment by pauldambra** [comment]
The default result for the algorithm is to return valid. My guess would be
that sortcode isn't in the list of sortcodes from valacdos.

**Comment by pauldambra** [comment]
Yep, if you look here https://github.com/pauldambra/ModulusChecker/blob/master/ModulusChecking/Resources/valacdos.txt#L199

232323 is not a sortcode the modulus algorithm handles (at least in the current version)

You can see here https://www.vocalink.com/media/2295/vocalink-validating-account-numbers-v410.pdf on page 9 that the first step in the algorithm is to check if the SortCode is in the modulus weight table and if not then to return that the account number is valid.

Really this means the algorithm cannot invalidate that combination rather than you can treat the combination as definitely valid.

**Comment by pauldambra** [comment]
And I've just checked the version of the modulus weight table that will be live from 6th March and that wouldn't change the result as it doesn't included 232323 either.

@chinthaka does that answer your question?

I've realised there's a lot of knowledge in my head that isn't in the project README. If this does answer you question I'll promote this as a usability bug to update the readme.

**Comment by chinthaka** [comment]
I can understand your point. But if the sort code is not valid shouldn't it return false? 

modulusChecker.CheckBankAccount(SortCode, AccountNumber) == false

Cheers

**Comment by pauldambra** [comment]
Sort codes in isolation are neither valid nor invalid.

A sort code that is not in the modulus table cannot be invalidated by the algorithm and as 232323 is not in the modulus table it is therefore valid or rather _not invalid_.

So here 

`modulusChecker.CheckBankAccount(232323, AccountNumber) == true` 

is correct for _any_ account number.

That doesn't mean that the combination does exist but rather that it _could_ exist

In fact, for any result from the modulus checking algorithm, it doesn't mean that the account and sort code combination have been provided to a customer by a bank. Only that it would be a valid combination if it were provided.

What the modulus checking algorithm does not do is assert whether or not a provided sort code maps to a UK bank. My understanding is that there are valid UK sort codes that are not in the modulus weight table.

The modulus checker is definitely returning the correct result against the spec here.

**Comment by chinthaka** [comment]
Thanks for your information.

**Comment by chinthaka** [comment]
That's good. Thanks

**Comment by pauldambra** [comment]
That's ok. Hope it helps! I'm really glad people are evaluating and using the checker!

I've added a usability bug to try and improve the section in the README that I intended to express this.

I'll think about whether a breaking change that introduce a tri-state logic response so that we can return true, false, or not_validatable

But would need to consider how that impacts existing users
